export const FETCHING_DBS = 'FETCHING_DBS'
export const FETCH_DBS_SUCCESS = 'FETCH_DBS_SUCCESS'
export const FETCH_DBS_FAILURE = 'FETCH_DBS_FAILURE'

export const FETCHING_COLLS = 'FETCHING_COLLS'
export const FETCH_COLLS_SUCCESS = 'FETCH_COLLS_SUCCESS'
export const FETCH_COLLS_FAILURE = 'FETCH_COLLS_FAILURE'
